Information:
  Title: amogusreal69
  Icon: icon.png
  Description: "A person in the internet that loves technology"
  Link: amogusreal69.me
  Theme: CatppuccinMocha

Connections:
  GitHub: amogusreal69
  GitLab:
  Bluesky:
  Twitter:
  Mastodon:
  Medium:
  Twitch:
  YouTube:
